#' @export
#' @title Overlays white blobs over an image.
#' @param image the image to modify.
#' @param blobLabels an equal sized image generated by \link{labelColonies}.
#' @description Masks an image with white blobs.
#' @return an image of the same dimensions.

overlayBlobs <- function(image, blobLabels) {
  image[blobLabels > 0] <- 1
  return(image)
}