#' @export
#' @title Overlays Colored Outlines Over Blobs
#' @param image the image matrix to modify.
#' @param mask an equal sized image generated by a label function,
#' e.g. \link{flow_labelPhase}.
#' @param color the outline color
#' @param thick if TRUE then outlines will be thickened
#' @description Given an image matrix and a mask of equal dimension, draws
#' outlines around the mask blobs on the image. Assumes image and mask are
#' of equal dimensions.
#' @return an image of the same dimensions.

overlayOutlines <- function(image, mask, color="red", thick=TRUE) {
  # paintObjects needs a logical matrix, so convert if need be
  if (typeof(mask) == "double") mask <- mask > 0
  image[image > 1] <- 1
  # Convert image to an EBImage Image object and set channel to color
  ebImage = EBImage::channel(EBImage::Image(image), 'rgb')
  # Paint outlines
  ebImage <- EBImage::paintObjects(mask, ebImage, thick=thick, col=color)
  return(ebImage)
}