#' @export
#' @title Overlays Colored Outlines Over Blobs
#' @param image the image matrix to modify.
#' @param blobLabels an equal sized image generated by a label function,
#' e.g. \link{flow_labelPhase}.
#' @param color the outline color
#' @description Given an image matrix and a mask of equal dimension, draws
#' outlines around the mask blobs on the image. Assumes image and mask are
#' of equal dimensions.
#' @return an image of the same dimensions.

overlayOutlines <- function(image, mask, col="red") {
  # paintObjects needs a logical matrix, so convert if need be
  if (typeof(image) == "double") image <- image > 0
  # Convert image to an EBImage Image object and set chanel to color
  im = channel(EBImage::Image(image), 'rgb')
  # Paint outlines
  return(EBImage::paintObjects(mask, im, thick=TRUE, color))
}